name: 'aemet_dbt'
version: '1.0.0'
config-version: 2

profile: aemet_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# --- CONFIGURACIÓN DE MODELOS
models:
  aemet_dbt:
    # 1. Capa Silver 
    staging:
      +materialized: view
      +schema: staging

    # 2. Capa Gold
    
    analytics:
      +materialized: table
      +schema: analytics

    # Desactiva los ejemplos por defecto de dbt
    example:
      +enabled: false